development:
  adapter: postgresql
  encoding: unicode
  database: pretender_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pretender_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: pretender_production
  pool: 25
  username: 
  password:
